@TuneVault_API_HostAddress = http://localhost:5093

GET {{TuneVault_API_HostAddress}}/weatherforecast/
Accept: application/json

### Kịch bản 1: Test lỗi Validation (Gửi tên quá ngắn)
POST {{TuneVault_API_HostAddress}}/api/test/pipeline
Content-Type: application/json

{
  "name": "a"
}

### Kịch bản 2: Test thành công
POST {{TuneVault_API_HostAddress}}/api/test/pipeline
Content-Type: application/json

{
  "name": "Sang Nguyễn"
}

### Kịch bản 3: Đăng ký tài khoản (Register)
POST {{TuneVault_API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@tunevault.com",
  "userName": "admin",
  "password": "Password123"
}

### Kịch bản 4: Đăng nhập lấy Token (Login)
POST {{TuneVault_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@tunevault.com",
  "password": "Password123"
}